[project]
name = "ml-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "freexiaochuan", email = "w2239559319@myyahoo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "torch>=2.14.0",
    "torch-vision>=0.1.6.dev0",
]

[project.scripts]
ml-learn = "ml_learn:main"
